### ISSUE TITLE
`milvus_cli` core dumps at any command. 

### ISSUE THREAD

**Issue by dove-young** [zilliztech/milvus_cli#62]
I installed `milvus_cli` and `readline` in RHEL 8. and `milvus_cli` core dumps at any command. 

```
[root@st2]# milvus_cli



  __  __ _ _                    ____ _     ___
 |  \/  (_) |_   ___   _ ___   / ___| |   |_ _|
 | |\/| | | \ \ / / | | / __| | |   | |    | |
 | |  | | | |\ V /| |_| \__ \ | |___| |___ | |
 |_|  |_|_|_| \_/  \__,_|___/  \____|_____|___|

Milvus cli version: 0.4.0
Pymilvus version: 2.3.0

Learn more: https://github.com/zilliztech/milvus_cli.


milvus_cli > connect
free(): invalid pointer
Aborted (core dumped)
```

```
[root@st2]# milvus_cli


  __  __ _ _                    ____ _     ___
 |  \/  (_) |_   ___   _ ___   / ___| |   |_ _|
 | |\/| | | \ \ / / | | / __| | |   | |    | |
 | |  | | | |\ V /| |_| \__ \ | |___| |___ | |
 |_|  |_|_|_| \_/  \__,_|___/  \____|_____|___|

Milvus cli version: 0.4.0
Pymilvus version: 2.3.0

Learn more: https://github.com/zilliztech/milvus_cli.


milvus_cli > help
free(): invalid pointer
Aborted (core dumped)
```

```
pip show pymilvus
Name: pymilvus
Version: 2.3.0
Summary: Python Sdk for Milvus
Home-page:
Author:
Author-email: Milvus Team <milvus-team@zilliz.com>
License:
Location: /root/jupyter/virtualenv/slack/lib/python3.10/site-packages
Requires: environs, grpcio, pandas, protobuf, ujson
Required-by: milvus-cli
```

**Comment by dove-young** [comment]
when I upgrade `pymilvus` to `2.3.3`, `milvus-cli` just failed to start. 

````

[root@st2]# pip install -U pymilvus
Requirement already satisfied: pymilvus in /root/jupyter/virtualenv/slack/lib/python3.10/site-packages (2.3.0)
Collecting pymilvus
  Using cached pymilvus-2.3.3-py3-none-any.whl.metadata (4.3 kB)

Using cached pymilvus-2.3.3-py3-none-any.whl (171 kB)
Installing collected packages: pymilvus
  Attempting uninstall: pymilvus
    Found existing installation: pymilvus 2.3.0
    Uninstalling pymilvus-2.3.0:
      Successfully uninstalled pymilvus-2.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
milvus-cli 0.4.0 requires pymilvus==2.3.0, but you have pymilvus 2.3.3 which is incompatible.
Successfully installed pymilvus-2.3.3

[root@st2]# pip show pymilvus
Name: pymilvus
Version: 2.3.3
Summary: Python Sdk for Milvus
Home-page:
Author:
Author-email: Milvus Team <milvus-team@zilliz.com>
License:
Location: /root/jupyter/virtualenv/slack/lib/python3.10/site-packages
Requires: environs, grpcio, minio, pandas, protobuf, requests, ujson
Required-by: milvus-cli
(slack)

[root@st2]# milvus_cli
dotenv_path = /root/jupyter/instana-slack-app/.env
Traceback (most recent call last):
  File "/root/jupyter/virtualenv/slack/lib/python3.10/site-packages/milvus_cli/utils.py", line 13, in getPackageVersion
    version = pkg_resources.require("milvus_cli")[0].version
  File "/root/jupyter/virtualenv/slack/lib/python3.10/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/root/jupyter/virtualenv/slack/lib/python3.10/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "/root/jupyter/virtualenv/slack/lib/python3.10/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pymilvus 2.3.3 (/root/jupyter/virtualenv/slack/lib/python3.10/site-packages), Requirement.parse('pymilvus==2.3.0'), {'milvus-cli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/jupyter/virtualenv/slack/bin/milvus_cli", line 5, in <module>
    from milvus_cli.scripts.milvus_cli import runCliPrompt
  File "/root/jupyter/virtualenv/slack/lib/python3.10/site-packages/milvus_cli/scripts/milvus_cli.py", line 1, in <module>
    from .connection_cli import *
  File "/root/jupyter/virtualenv/slack/lib/python3.10/site-packages/milvus_cli/scripts/connection_cli.py", line 2, in <module>
    from .helper_cli import show, getList
  File "/root/jupyter/virtualenv/slack/lib/python3.10/site-packages/milvus_cli/scripts/helper_cli.py", line 10, in <module>
    from utils import WELCOME_MSG, EXIT_MSG, Completer, getPackageVersion
  File "/root/jupyter/virtualenv/slack/lib/python3.10/site-packages/milvus_cli/utils.py", line 177, in <module>
    WELCOME_MSG = msgTemp.safe_substitute(cli=getPackageVersion(), py=__version__)
  File "/root/jupyter/virtualenv/slack/lib/python3.10/site-packages/milvus_cli/utils.py", line 15, in getPackageVersion
    raise ParameterException(
Types.ParameterException: Could not get version under single executable file mode.
```

**Comment by nameczz** [comment]
milvus_cli 0.4.0 only test with pymilvus 2.3.0.  
Not sure if it is compatible with pymilvus 2.3.x. Will test it asap

**Comment by nameczz** [comment]
Use milvus 0.4.1 and pymilvus 2.3.4 is working fine for me. Please have a try

**Comment by SuperAspen** [comment]
> Use milvus 0.4.1 and pymilvus 2.3.4 is working fine for me. Please have a try @dove-young

I install milvus cli 0.4.1 and pymilvus 2.3.4, still got the same error. Could you tell me more about your solution? Thanks.
By the way I also tried milvus cli 0.4.2, same error.


  __  __ _ _                    ____ _     ___
 |  \/  (_) |_   ___   _ ___   / ___| |   |_ _|
 | |\/| | | \ \ / / | | / __| | |   | |    | |
 | |  | | | |\ V /| |_| \__ \ | |___| |___ | |
 |_|  |_|_|_| \_/  \__,_|___/  \____|_____|___|

Milvus cli version: 0.4.1
Pymilvus version: 2.3.4

Learn more: https://github.com/zilliztech/milvus_cli.


milvus_cli > help
free(): invalid pointer
Aborted (core dumped)

**Comment by dove-young** [comment]
I got clue about this issue. https://pypi.org/project/readline/. 

Replace `readline` module by `gnureadline`, the this issue is fixed.  @SuperAspen
