### ISSUE TITLE
An error occurred during milvus_cli  installation 

### ISSUE THREAD

**Issue by suyestyle** [zilliztech/milvus_cli#83]
```
# python --version
Python 3.12.3
# openssl --version
OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
# 

```

```
# pip install milvus_cli-0.4.2-py3-none-any.whl 

Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
Processing ./milvus_cli-0.4.2-py3-none-any.whl
Collecting Click==8.0.1 (from milvus-cli==0.4.2)
  Using cached http://mirrors.tencentyun.com/pypi/packages/76/0a/b6c5f311e32aeb3b406e03c079ade51e905ea630fc19d1262a46249c1c86/click-8.0.1-py3-none-any.whl (97 kB)
Collecting pymilvus==2.3.4 (from milvus-cli==0.4.2)
  Using cached http://mirrors.tencentyun.com/pypi/packages/02/8d/8c1362746d528c4fe4d7d35fdf8de3457f1cfe9e65d02a0999647b72b72f/pymilvus-2.3.4-py3-none-any.whl (172 kB)
Collecting tabulate==0.8.9 (from milvus-cli==0.4.2)
  Using cached http://mirrors.tencentyun.com/pypi/packages/ca/80/7c0cad11bd99985cfe7c09427ee0b4f9bd6b048bd13d4ffb32c6db237dfb/tabulate-0.8.9-py3-none-any.whl (25 kB)
Requirement already satisfied: requests==2.31.0 in /usr/lib/python3.12/site-packages (from milvus-cli==0.4.2) (2.31.0)
Collecting grpcio<=1.58.0,>=1.49.1 (from pymilvus==2.3.4->milvus-cli==0.4.2)
  Using cached http://mirrors.tencentyun.com/pypi/packages/5d/a2/781bae6df87dfd31115b24b1fe01213ef29caf9dbd0b8c1688c59aebf617/grpcio-1.58.0.tar.gz (24.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      <string>:43: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ti6kc_fj/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ti6kc_fj/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ti6kc_fj/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ti6kc_fj/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 292, in <module>
        File "<string>", line 226, in check_linker_need_libatomic
        File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'c++'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by nameczz** [comment]
If you want to install 0.4.2 version, you can try `pip3 install milvus_cli==0.4.2`. @suyestyle

**Comment by suyestyle** [comment]
This error may be related to the gcc environment, I used the command [yum install g++ gcc] to install the gcc environment after re-installing milvus_cli, found that the error was still reported, the error message is like the following

```
      cc1: warning: command-line option ‘-std=c++14’ is valid for C++/ObjC++ but not for C
      creating None
      creating None/tmp
      creating None/tmp/tmpz4gja2dg
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -I/usr/include/python3.12 -c /tmp/tmpz4gja2dg/a.c -o None/tmp/tmpz4gja2dg/a.o
      Traceback (most recent call last):
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/tmp/pip-install-1a0ys1gc/grpcio_ce8c2701034f43569109bc0bdd9eae27/src/python/grpcio/_spawn_patch.py", line 58, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(f"command {cmd!r} failed with exit code {exitcode}")
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-1a0ys1gc/grpcio_ce8c2701034f43569109bc0bdd9eae27/src/python/grpcio/commands.py", line 313, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-1a0ys1gc/grpcio_ce8c2701034f43569109bc0bdd9eae27/src/python/grpcio/_parallel_compile_patch.py", line 64, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/usr/lib64/python3.12/multiprocessing/pool.py", line 367, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.12/multiprocessing/pool.py", line 774, in get
          raise self._value
        File "/usr/lib64/python3.12/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
                          ^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.12/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
                 ^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-1a0ys1gc/grpcio_ce8c2701034f43569109bc0bdd9eae27/src/python/grpcio/_parallel_compile_patch.py", line 59, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 190, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 614, in <module>
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/tmp/pip-install-1a0ys1gc/grpcio_ce8c2701034f43569109bc0bdd9eae27/src/python/grpcio/commands.py", line 317, in build_extensions
          raise CommandError(
      commands.CommandError: Failed `build_ext` step:
      Traceback (most recent call last):
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/tmp/pip-install-1a0ys1gc/grpcio_ce8c2701034f43569109bc0bdd9eae27/src/python/grpcio/_spawn_patch.py", line 58, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(f"command {cmd!r} failed with exit code {exitcode}")
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-1a0ys1gc/grpcio_ce8c2701034f43569109bc0bdd9eae27/src/python/grpcio/commands.py", line 313, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-1a0ys1gc/grpcio_ce8c2701034f43569109bc0bdd9eae27/src/python/grpcio/_parallel_compile_patch.py", line 64, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/usr/lib64/python3.12/multiprocessing/pool.py", line 367, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.12/multiprocessing/pool.py", line 774, in get
          raise self._value
        File "/usr/lib64/python3.12/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
                          ^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.12/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
                 ^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-1a0ys1gc/grpcio_ce8c2701034f43569109bc0bdd9eae27/src/python/grpcio/_parallel_compile_patch.py", line 59, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/tmp/pip-build-env-k3evp3bk/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 190, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
Failed to build grpcio
ERROR: Could not build wheels for grpcio, which is required to install pyproject.toml-based projects

```

**Comment by suyestyle** [comment]
The following several installation methods have been tried, but the installation has failed

```
Install from PyPI (Recommended)
Run pip install pymilvus==2.3.4 Run pip install milvus-cli==0.4.2

Install from a tarball
Download the [latest release](https://github.com/zilliztech/milvus_cli/releases/latest) of  milvus_cli-<version>.tar.gz.
Run pip install milvus_cli-<version>.tar.gz.
Install from source code
Run git clone https://github.com/zilliztech/milvus_cli.git.
Run cd milvus_cli.
Run pip install --editable .
Install from an executable file
```

**Comment by nameczz** [comment]
@suyestyle  Sorry, I'm not very familiar with it.
My idea is you can try to create a new system environment for cli, like docker? Hope can help you.
