### ISSUE TITLE
why "docker run -it zilliz/milvus_cli:latest"  is error

### ISSUE THREAD

**Issue by linyu0923** [zilliztech/milvus_cli#86]
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 12: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/usr/local/bin/milvus_cli", line 5, in <module>
    from milvus_cli.scripts.milvus_cli import runCliPrompt
  File "/usr/local/lib/python3.8/site-packages/milvus_cli/scripts/milvus_cli.py", line 1, in <module>
    from .connection_cli import *
  File "/usr/local/lib/python3.8/site-packages/milvus_cli/scripts/connection_cli.py", line 2, in <module>
    from .helper_cli import show, getList
  File "/usr/local/lib/python3.8/site-packages/milvus_cli/scripts/helper_cli.py", line 1, in <module>
    from .init_cli import cli
  File "/usr/local/lib/python3.8/site-packages/milvus_cli/scripts/init_cli.py", line 9, in <module>
    from Cli import MilvusCli
  File "/usr/local/lib/python3.8/site-packages/milvus_cli/Cli.py", line 1, in <module>
    from Connection import MilvusConnection
  File "/usr/local/lib/python3.8/site-packages/milvus_cli/Connection.py", line 1, in <module>
    from pymilvus import connections, list_collections
  File "/usr/local/lib/python3.8/site-packages/pymilvus/__init__.py", line 14, in <module>
    from .client.prepare import Prepare
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 12, in <module>
    from pymilvus.orm.schema import CollectionSchema
  File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 16, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.8/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(_dependency)
  File "/usr/local/lib/python3.8/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/usr/local/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt

**Comment by linyu0923** [comment]
I find the File "/usr/local/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in from numpy.core._multiarray_umath import  and exec the code no error

python3 
Python 3.8.19 (default, Jul 30 2024, 20:05:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> import functools
>>> import os
>>> from numpy.core._multiarray_umath import (
...     add_docstring, implement_array_function, _get_implementing_args)
>>>

**Comment by linyu0923** [comment]
Python 3.8.19 (default, Jul 30 2024, 20:05:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> import functools
>>> import os
>>> from numpy.core._multiarray_umath import (
...     add_docstring, implement_array_function, _get_implementing_args)
>>>

**Comment by nameczz** [comment]
![image](https://github.com/user-attachments/assets/57bdc9e0-eebf-43f7-a33e-d256a6a16b72)
Already fixed
